### ISSUE TITLE
Does not work with Symfony 7

### ISSUE THREAD

**Issue by OlegKunitsyn** [nanofelis/NanofelisJsonRpcBundle#141]
```
"require": {
        "php": ">=8.2",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "nanofelis/json-rpc-bundle": "^3.3",
        "php-amqplib/rabbitmq-bundle": "^2.14",
        "symfony/amqp-messenger": "7.0.*",
        "symfony/console": "7.0.*",
        "symfony/dotenv": "7.0.*",
        "symfony/flex": "^2",
        "symfony/framework-bundle": "7.0.*",
        "symfony/runtime": "7.0.*",
        "symfony/yaml": "7.0.*"
    },
```

```
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/RpcServices/'
    App\RpcServices\:
        resource: '../src/RpcServices/'
        tags:
            - 'nanofelis_json_rpc'

```

```bash
curl -X POST localhost:8000/ -d '{"jsonrpc": "2.0", "method": "myService.add", "params": [1, 2], "id": "test-call"}' 
```
`{"jsonrpc":"2.0","error":{"code":-32602,"message":"invalid params","data":null},"id":"test-call"}`
